# Generated by Django 5.0.1 on 2024-02-07 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_app', '0005_rename_name_payment_names'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='names',
            new_name='name',
        ),
    ]
